site_name: Test

site_url: https://zschreib.github.io


docs_dir: docs/

theme:
    name: readthedocs

pages:
    - Home: index.md
    - About: about.md
    - User Guide:
        - Instructions: user-guide/instructions.md
        
extra:
    version: 0.1
    
  